apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  project: default
  source:
    repoURL: https://github.com/ankit0906/spark-app.git
    targetRevision: HEAD
    path: argo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: true
    prune: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
  hooks:
    - name: auto-sync
      command: [argocd-image-updater]
      source:
        resource:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ankit-app
            namespace: default
          hook: Sync
      destination:
        resource:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ankit-app
            namespace: default
      runOn:
        change: true
      when:
        annotationSelector: argocd-image-listen
