apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  annotations:
    argocd-image-listen: '{"image": "ankitdockerhub1/images", "tag": "latest"}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ankitdockerhub1/images:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080

