name: CI/CD Pipeline

on:
  push:
    branches:
      - feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          
          push: true
          tags: ankitdockerhub1/images:${{ steps.short_sha.outputs.short_sha}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          

      - name: Update manifests file
        run: |
          sed -i "s|image: ankitdockerhub1/images:[^ ]*|image: ankitdockerhub1/images:${short_sha}|g" argo/deployment.yaml
      - name: push changes to master
        run: |    
          git config --global user.name "ankit0906"
          git config --global user.email "kothawadeankit90@gmail.com"
          git add .
          git commit -m "added new feature"
          git push origin master
    

     

