name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: |
          docker build -t scala-v2 .
          docker login -u ankitdockerhub1 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag scala-v2 ankitdockerhub1/scala-v2
          docker push ankitdockerhub1/scala-v2

