name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          commit_sha=$(git rev-parse --short HEAD)
          docker build -t myspark:${commit_sha} ./Dockerfile
          echo "::set-output name=image-tag::myspark:${commit_sha}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push myspark:${commit_sha}

      - name: Update manifests file
        run: |
          sed -i "s+myspark:latest+myspark:${commit_sha}+g" deployment.yaml
          echo "${commit_sha}" > latest_commit.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "kothawadeankit90@gmail.com"
          git config --global user.name "ankit0906"
          git add deployment.yaml latest_commit.txt
          git commit -m "Update Docker image tag and latest commit ID"
          git push

