name: CI/CD Pipeline

on:
  push:
    branches:
      - feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: get commit id
        id: commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ankitdockerhub1/images:${{ steps.commit_id.outputs.commit_id}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Update manifests file 
        
        run: |
          COMMIT_ID:$(git rev-parse --short HEAD)
          sed -i "s|image: ankitdockerhub1/images:[^ ]*|image: ankitdockerhub1/images:${COMMIT_ID}|g" argo/deployment.yaml

      - name: push changes to master
        run: |    
          git config --global user.name "ankit0906"
          git config --global user.email "kothawadeankit90@gmail.com"
          git add .
          git commit -m "added new feature"
          git push origin master
    

     

